"use client";
import Link from "next/link";
import { HomeIcon, ArrowLeftIcon } from "@heroicons/react/24/solid";

export default function EnergyLesson() {
  return (
    <div className="min-h-screen bg-slate-900 text-white px-6 py-12 flex justify-center">
      <div className="max-w-3xl bg-slate-800 p-8 rounded-2xl shadow-lg overflow-y-auto h-[90vh]">
        <h1 className="text-4xl font-bold text-purple-400 mb-8 text-center">
          Renewable Energy
        </h1>

        <div className="text-gray-300 space-y-4 text-lg leading-relaxed">
           <p>
            Renewable energy comes from natural sources that are constantly replenished, such as sunlight, wind, water, and biomass. Unlike fossil fuels, renewable energy is sustainable and has minimal impact on the environment.
          </p>
          <p>
            Transitioning to renewable energy reduces greenhouse gas emissions, mitigates climate change, and decreases dependence on finite fossil fuels.
          </p>

           <h2 className="text-2xl font-semibold text-purple-300 mt-6 mb-4">Why Renewable Energy Matters</h2>
          <p>
            Using renewable energy helps protect ecosystems, reduces air and water pollution, and provides reliable energy for communities. It is also key to achieving the United Nations Sustainable Development Goals, particularly SDG 7: Affordable and Clean Energy.
          </p>

           <h2 className="text-2xl font-semibold text-purple-300 mt-6 mb-4">Types of Renewable Energy</h2>
          <ul className="list-disc list-inside mb-6">
            <li><strong>Solar:</strong> energy harnessed from sunlight using solar panels.</li>
            <li><strong>Wind:</strong> energy generated by wind turbines.</li>
            <li><strong>Hydropower:</strong> energy from flowing water in rivers or dams.</li>
            <li><strong>Geothermal:</strong> energy from the Earth's internal heat.</li>
            <li><strong>Biomass:</strong> energy derived from organic materials like wood, crop waste, and animal waste.</li>
          </ul>

           <h2 className="text-2xl font-semibold text-purple-300 mt-6 mb-4">Benefits</h2>
          <ul className="list-disc list-inside mb-6">
            <li>Reduces carbon emissions and air pollution.</li>
            <li>Promotes energy security and sustainability.</li>
            <li>Supports green jobs and economic growth.</li>
            <li>Decreases dependence on fossil fuels.</li>
            <li>Provides affordable energy in remote and rural areas.</li>
          </ul>

           <h2 className="text-2xl font-semibold text-purple-300 mt-6 mb-4">Challenges</h2>
          <ul className="list-disc list-inside mb-6">
            <li>Intermittent energy supply (sunlight and wind depend on weather conditions).</li>
            <li>High initial infrastructure and installation costs.</li>
            <li>Requires energy storage solutions like batteries.</li>
            <li>Need for updated grids and smart energy management systems.</li>
          </ul>

           <h2 className="text-2xl font-semibold text-purple-300 mt-6 mb-4">How You Can Help</h2>
          <ul className="list-disc list-inside mb-6">
            <li>Install solar panels or support community renewable energy projects.</li>
            <li>Advocate for clean energy policies in your city or country.</li>
            <li>Use energy efficient appliances and reduce energy consumption at home.</li>
            <li>Educate others about the benefits of renewable energy and sustainability.</li>
            <li>Support companies and initiatives that focus on renewable energy development.</li>
          </ul>
        </div>

         <div className="mt-10 flex gap-4 justify-center">
          <Link
            href="/lessons"
            className="bg-slate-700 px-6 py-2 rounded-xl hover:bg-slate-600 flex items-center gap-2"
          >
            <ArrowLeftIcon className="w-5 h-5 text-white" />
          </Link>

          <Link
            href="/"
            className="bg-slate-700 px-6 py-2 rounded-xl hover:bg-slate-600 flex items-center gap-2"
          >
            <HomeIcon className="w-5 h-5 text-white" />
          </Link>
        </div>
      </div>
    </div>
  );
}
